/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdbool.h>
#include "gpio_address_map.h"

void Setup_GPIO();
void SysTick_Init();
void delay_ms(uint32_t ms);

void westRed();
void westYellow();
void westGreen();
void eastRed();
void eastYellow();
void eastGreen();

int main(void)
{
	Setup_GPIO();
	SysTick_Init();

	while(true) {

		westRed();
	}
}

void Setup_GPIO() {
	// Enable clock to GPIOA, GPIOC, and GPIOF
	RCC->AHB1ENR |= (1UL << 2);

	// Allow clock to stabilize
	//while((RCC->AHB1ENR | (1UL << 0) | (1UL << 2) | (1UL << 5)) != (1UL << 0) | (1UL << 2) | (1UL << 5)) {};
	while((RCC->AHB1ENR & (1UL << 2)) != (1UL << 2)) {};

	// ---------- Set output pins ----------

	// PINS 10 and 12 for GPIOC
	GPIOC->MODER &= ~(3UL << (PIN_10 * 2)); // Clear data between bits 21-20
	GPIOC->MODER |= (1UL << (PIN_10 * 2)); // Pin 10 enable


	// ---------- Set Push-Pull ----------
	GPIOC->OTYPER &= ~(1UL << PIN_10);


	// ---------- Set digital enable ----------
	GPIOC->ODR |= (1UL << PIN_10);
}


void SysTick_Init() {
	SYSTICK->LOAD = SYSTICK_LOAD; // Set to 1ms interval
	SYSTICK->VAL = 0; // Set counter to 0 to clear/reset
	SYSTICK->CTRL = (1UL << 2) | (1UL << 0); // Clock source | Enable
}

void delay_ms(uint32_t ms) {
	for(uint32_t i = 0; i < ms; i++) {
		while((SYSTICK->CTRL & (1UL << 16)) == 0);
	}
}

void westRed() {
	// Initial State
	GPIOC->ODR |= (1UL << PIN_10);
}


/*void westYellow() {

}

void westGreen() {

}

void eastRed() {

}

void eastYellow() {

}

void eastGreen() {

}
*/
