/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdbool.h>
#include "gpio_address_map.h"

void SetUp_GPIO();
void SysTick_Init();
void delay_ms(uint32_t ms);

int main(void)
{
	SetUp_GPIO();
	SysTick_Init();

	// Initial state: turn off LED
	GPIOC->ODR &= ~(1UL << PIN_10);

    /* Loop forever */
	while(true) {
	    // Turn on
		GPIOC->ODR |= (1UL << PIN_10);
		// Delay
		delay_ms(500);

		// Turn off
		GPIOC->ODR &= ~(1UL << PIN_10);
		// Delay
		delay_ms(500);
	}
}

void SetUp_GPIO() {
	// Initialize STM32 system clock to the GPIO modules
	// 0UL means off (0 times any number is 0), 1UL means on
	RCC->AHB1ENR |= (1UL << 2); // Port C

	// Allow time for the clock to stabilize
	while((RCC->AHB1ENR & (1UL << 2)) != (1UL << 2)) {};

	// Set output pins (I am using PIN 10, so MODER10[1:0] = 01)
	// Furthermore, MODER10 are between bits 21-20
	GPIOC->MODER &= ~(3UL << (PIN_10 * 2)); // clearing data within the bits register 21-20
	GPIOC->MODER |= (1UL << (PIN_10 * 2)); // 01 is output mode

	// Set pull-up or pull-down
	// PUPDR refers to internal components like the button on a STM32
	// Whereas, OTYPER deals with the pin driving current
	GPIOC->OTYPER &= ~(1UL << PIN_10); // setting 0 to pin 10 to act as a push-pull

	// Set digital enable
	GPIOC->ODR |= (1UL << PIN_10);
}

void SysTick_Init() {
	SYSTICK->LOAD = SYSTICK_LOAD; // The interval is set to 1ms
	SYSTICK->VAL = 0; // This acts as a counter, so initialize to 0 to clear/reset counter
	SYSTICK->CTRL = (1UL << 2) | (1UL << 0); // Enable processor clock (CLKSOURCE) and counter (ENABLE)
}

void delay_ms(uint32_t ms) {
	for (uint32_t i = 0; i < ms; i++) {
		while ((SYSTICK->CTRL & (1UL << 16)) == 0); // While COUNTFLAG == 0, then continue to wait (1ms has not passed yet)
	}
}
